jobs:
  run:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: wow-actions/potential-duplicates@4d4ea0352e0383859279938e255179dd1dbb67b5
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        comment: "We have found issues that are potential duplicates: {{#issues}}\n\
          \  - #{{ number }} ({{ accuracy }}%)\n{{/issues}}\n\nIf any of the issues\
          \ listed above are a duplicate, please consider closing this issue & upvoting/commenting\
          \ the original one.\nAlternatively, if neither of the listed issues addresses\
          \ your feature/bug, keep this issue open."
        exclude: regression
        filter: ''
        label: potential-duplicate
        reactions: confused
        state: all
        threshold: 0.6
name: Potential Duplicate Issues
on:
  repository_dispatch:
    types: trigger-ga___duplicate-issues-detector.yaml
