jobs:
  call-license-check:
    permissions:
      pull-requests: write
    secrets:
      gitlabAPIToken: ${{ secrets.ECLIPSE_GITLAB_API_TOKEN }}
    uses: eclipse/dash-licenses/.github/workflows/mavenLicenseCheck.yml@master
    with:
      projectId: eclipse.jdt.ls
      submodules: recursive
name: License vetting status check
on:
  repository_dispatch:
    types: trigger-ga___licensecheck.yml
